# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages on PR

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

env:
  PREVIEW_BRANCH: gh-pages

concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Replace baseurl
        run: |
          sed -i "s@\(baseurl: .*\)@\1\/pr-preview\/pr-${{github.event.number}}@" _config.yml
          cat _config.yml
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pr_deploy
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pr_deploy.outputs.base_path }}"
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
          JEKYLL_ENV: production
      - name: Preview deployment
        id: preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
          preview-branch: ${{ env.PREVIEW_BRANCH }}
          comment: true
      - name: Output base URL
        env: 
          ECHO: ${{ toJson(steps.preview.outputs) }}
        run: echo "$ECHO"